### ISSUE TITLE
能否抽空增加源码注释

### ISSUE THREAD

**Issue by n9sr5y** [frejs/fre#327]
如题，中英文都可以

**Comment by yisar** [comment]
编注释太难了。。。

**Comment by n9sr5y** [comment]
哈哈，有利于更多人加入，也更有利于后续重构。举个例子（虽然不确切），像“d: IFiber”（），是代表什么，只能通过上下文联系得出。像这种，可以增加下注释，像“export type SetStateAction<S> = S | ((prevState: S) => S)”一看就清楚的，就暂时不用啦，让社区的人维护合并进来。

**Comment by yisar** [comment]
那个类型不是我写的，对我而言，写注释比写代码还难

**Comment by yisar** [comment]
重构了，已经没得 d 变量了-_-||，我发现注释有利于提升测试覆盖率，之后编一点

**Comment by Flcwl** [comment]
不写注释可不好开源参与维护

**Comment by yisar** [comment]
我又重构了一波，现在没有很奇怪的命名了，注释的话我也不晓得怎么加比较好
